### ISSUE TITLE
Addition of StyledTextbox

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/awesome-umbraco#25]

**Comment by naepalm** [comment]
I _love_ styled textbox. It's one of my favorite "tiny packages" right now that adds so much love for the client. And it's super easy to swap in on older projects, too, since it doesn't change textbox values at all!

**Comment by leekelleher** [comment]
@naepalm - I love it too! Using it on most new projects now.

Would be ace if you could send a PR to add it to the list. 😎
