### ISSUE TITLE
Addition of Terratype

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/awesome-umbraco#26]

**Comment by jamiepollock** [comment]
I've used Terratype for my latest Umbraco 7.6 project (caveat: not deployed out of local just yet). 

It's an amazing package which is has so many amazing configuration options, although I could imagine that might bewilder some people. It's really easy to use in views as it comes with its own HtmlHelper extensions.

All in all, a worthy addition to the list. I wish I could provide some experience of using it a live environment but it's an impressive backoffice tool to develop with.

**Comment by leekelleher** [comment]
Cool. Jonathan gave us a demo of it at umBristol the other night, looked
great!

Do you want to submit a PR to add it to the list?

**Comment by jamiepollock** [comment]
@leekelleher can do :)
