### ISSUE TITLE
Suggestion: Remove "Umbraco products" category

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/awesome-umbraco#27]
Suggestion to remove the **Umbraco products** category, by relocating **Umbraco Forms** to the Form Builder subcategory (under Backoffice Extensions) and **Courier** to a new subcategory (under Developer Tools) called "Deployment".

**Comment by naepalm** [comment]
I agree. I don't think they need to be specified, or if they do, just put a note next to them such as (Developed by Umbraco)?

**Comment by kjac** [comment]
An Umbraco newcomer reading this list would probably like to know both if a package is supported by Umbraco HQ and if it's a commercial one or not. On the other hand the distinction between Umbraco products and non-Umbraco products might not make a whole lot of sense to said newcomer. 

As long as the list states "backed by Umbraco" and "commercial offering" I think it makes sense to merge the categories.
