### ISSUE TITLE
Review list

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/awesome-umbraco#7]
Review the list, make sure everything is still relevant.

Also review the recent Our Umbraco post, there are some gems in there...
https://our.umbraco.org/forum/using-umbraco-and-getting-started/81789-what-would-be-your-top-5-plugins-for-an-umbraco-website

**Comment by leekelleher** [comment]
Some packages that I think should be considered for the list...

- uEditorNotes
- UnVersion
- DocTypeGridEditor
- Courier Contrib Resolvers (essential for any UmbracoCloud project)
- StyledTextbox
- Switcher
- Diplo Trace Log
- AngularGoogleMaps (or review its successor, Terratype?)
- RJP.MultiUrlPicker (or other LinkPicker?)

**Comment by leekelleher** [comment]
Sir Trevor has become inactive (hasn't been updated in a 2.5 years), once Stacked Content is released (on Our Umbraco), it could replace Sir Trevor?

**Comment by Hendy** [comment]
Hi Lee, how about the [Azure Table Storage Logger](https://github.com/CrumpledDog/Umbraco-AzureLogger) or is that a bit too niche ?

**Comment by leekelleher** [comment]
@Hendy I haven't used it myself, but if you think it's awesome, then yes, lets add it to the list! 🤘

**Comment by greystate** [comment]
+1 for Switcher - probably the only one I add by default, before having researched what I might even need :-)

**Comment by leekelleher** [comment]
@greystate - yup, I'm using Switcher on most of our new projects now.

Send us a PR man! Your name will be in lights... _um, well, in a commit_.

![coollogo_com-113161072](https://cloud.githubusercontent.com/assets/209066/24949799/cb0d9758-1f66-11e7-85bc-10b5e34e55fb.png)

**Comment by greystate** [comment]
Oh that's a nice sign for my Ninja persona!

**Comment by leekelleher** [comment]
Closing this one. Raised my other suggestions as separate tickets: #23, #24, #25, #26
